# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nav_bar',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
