# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_okr'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Specialization'),
        ),
    ]
