# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_specialization_okr'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='day_student',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='night_student',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
