# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170108_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('okr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.OKR')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='statistic',
            name='year',
            field=models.ManyToManyField(blank=True, null=True, to='core.Year'),
        ),
    ]
