# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170108_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='year',
        ),
        migrations.AddField(
            model_name='statistic',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Year'),
        ),
    ]
