# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_year_okr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
    ]
