# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170108_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='okr',
            name='statistic_need',
            field=models.BooleanField(default=False),
        ),
    ]
