# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170108_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_block',
            name='grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Grup'),
        ),
    ]
