# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_schedule_block_grup'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_block',
            name='up_week',
            field=models.BooleanField(default=False),
        ),
    ]
