# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_student_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_start', models.DateField()),
                ('first_end', models.DateField()),
                ('second_start', models.DateField()),
                ('second_end', models.DateField()),
            ],
        ),
    ]
