# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_olimp_olimp_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='libery',
            name='slug',
            field=models.CharField(default='dd', max_length=250),
            preserve_default=False,
        ),
    ]
